version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/web-client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "composer"
    directory: "/core-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
